Add files via upload
MaksimLukankin/hometask pull request #5
Opened 2020-10-04 20:59 UTC by MaksimLukankin

2020-10-07 16:03 UTC, MathPracticum requested changes
доделать 5-6

2020-10-24 08:50 UTC, MathPracticum requested changes
удалить лишние файлы, а untitled14 переименовать понятным образом

2020-10-24 13:57 UTC, MaksimLukankin commented
Удалил ненужное, переименовал нужное

2020-11-02 10:30 UTC, MathPracticum approved these changes

2020-11-02 13:04 UTC, merged